### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by baosir529a** [AONE-NLP/ABSA-AOAN#1]
你好请问您能分享一下处理过的数据集吗，谢谢你！！！

**Comment by AONE-NLP** [comment]
您好，数据集已经上传在github项目中了
        
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
        
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年8月26日 13:52
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              [AONE-NLP/ABSA-AOAN] 数据集 (Issue #1)
        
      
    
  

你好请问您能分享一下处理过的数据集吗，谢谢你！！！

**Comment by hodorxxx** [comment]
您好，数据集已更新在项目中

**Comment by baosir529a** [comment]
loading tokenizer: twitter_tokenizer.dat
Traceback (most recent call last):
  File "E:/代码/ABSA-AOAN-main/train.py", line 298, in <module>
    main()
  File "E:/代码/ABSA-AOAN-main/train.py", line 293, in main
    ins = Instructor(opt)
  File "E:/代码/ABSA-AOAN-main/train.py", line 62, in __init__
    self.model = opt.model_class(embedding_matrix, opt).to(opt.device)
  File "E:\代码\ABSA-AOAN-main\models\AOAN.py", line 35, in __init__
    self.bert_SA = SelfAttention(bert.config, opt)
AttributeError: 'numpy.ndarray' object has no attribute 'config'
loading embedding_matrix: 300_twitter_embedding_matrix.dat
运行train为什么会显示这个错误

**Comment by liuzh00** [comment]
作者您好，在复现您论文的过程中我遇到了一些问题：1.input_cols中的aspect_boundary在模型中是不是没有使用  2.在根据您论文中提到的超参数进行复现时，效果始终很难接近您的结果。希望您在百忙中能解答我的困惑，祝您学业顺利！
![FRGEX2UZTV F$}))RK518J](https://github.com/AONE-NLP/ABSA-AOAN/assets/125945273/22ff284d-0ea0-44fa-8f66-8a84869fe158)
