### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './datasets/semeval14/Laptops_Train.xml.seg.graph'

### ISSUE THREAD

**Issue by Goose0513** [AONE-NLP/ABSA-AOAN#2]
您好，在运行train.py文件过程中产生了如下报错：
Traceback (most recent call last):
  File "D:/CQUPT/Learning/codes/ABSA-AOAN-main/ABSA-AOAN-main/train.py", line 286, in <module>
    main()
  File "D:/CQUPT/Learning/codes/ABSA-AOAN-main/ABSA-AOAN-main/train.py", line 281, in main
    ins = Instructor(opt)
  File "D:/CQUPT/Learning/codes/ABSA-AOAN-main/ABSA-AOAN-main/train.py", line 56, in __init__
    self.trainset = ABSADataset(opt.dataset_file['train'], tokenizer)
  File "D:\CQUPT\Learning\codes\ABSA-AOAN-main\ABSA-AOAN-main\data_utils.py", line 148, in __init__
    fin = open(fname + '.graph','rb')
FileNotFoundError: [Errno 2] No such file or directory: './datasets/semeval14/Laptops_Train.xml.seg.graph'

Process finished with exit code 1
请问该文件在哪里寻找呢?或者应该怎样修改代码？非常感谢

**Comment by AONE-NLP** [comment]
已上传在datasets中
        
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
        
  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        8/31/2023 17:33
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              [AONE-NLP/ABSA-AOAN] FileNotFoundError: [Errno 2] No such file or directory: './datasets/semeval14/Laptops_Train.xml.seg.graph' (Issue #2)
        
      
    
  

您好，在运行train.py文件过程中产生了如下报错：
Traceback (most recent call last):
File "D:/CQUPT/Learning/codes/ABSA-AOAN-main/ABSA-AOAN-main/train.py", line 286, in 
main()
File "D:/CQUPT/Learning/codes/ABSA-AOAN-main/ABSA-AOAN-main/train.py", line 281, in main
ins = Instructor(opt)
File "D:/CQUPT/Learning/codes/ABSA-AOAN-main/ABSA-AOAN-main/train.py", line 56, in init
self.trainset = ABSADataset(opt.dataset_file['train'], tokenizer)
File "D:\CQUPT\Learning\codes\ABSA-AOAN-main\ABSA-AOAN-main\data_utils.py", line 148, in init
fin = open(fname + '.graph','rb')
FileNotFoundError: [Errno 2] No such file or directory: './datasets/semeval14/Laptops_Train.xml.seg.graph'
Process finished with exit code 1
请问该文件在哪里寻找呢?或者应该怎样修改代码？非常感谢
